package ru.DmN.pht.std.compiler.java

import ru.DmN.pht.base.compiler.java.compilers.NCDefault
import ru.DmN.pht.base.utils.ModuleCompilers
import ru.DmN.pht.std.Pihta
import ru.DmN.pht.std.compilers.*
import ru.DmN.pht.std.processors.NRMath
import ru.DmN.pht.std.ups.NUPMath

object PihtaJava : ModuleCompilers(Pihta) {
    override fun onInitialize() {
        // a
        add("!add",         NCMath)
        add("!aget",        NCAGet)
        add("!alias-type",  NCSkip)
        add("!and",         NCMath)
        add("array-size",   NCArraySize)
        add("!as",          NCAs)
        add("!aset",        NCASet)
        // b
        add("!bit-shift-left",  NCMath)
        add("!bit-shift-right", NCMath)
        add("body",         NCBody)
        // c
        add("!cls",         NCClass)
        add("ctor",         NCDefn)
        add("!cycle",       NCCycle)
        // d
        add("!dec",         NCIncDec)
        add("!def",         NCDef)
        add("!defn",        NCDefn)
        add("!div",         NCMath)
        // e
        add("efield",       NCEField)
        add("efn",          NCDefn)
        add("!eq",          NCCompare)
        // f
        add("!fget",        NCFGet)
        add("!field",       NCField)
        add("!fn",          NCFn)
        add("fset",         NCFSet)
        // g
        add("get",          NCGetA)
        add("get-or-name!", NCGetB)
        add("!great",       NCCompare)
        add("!great-or-eq", NCCompare)
        // i
        add("if",           NCIf)
        add("!inc",         NCIncDec)
        add("!itf",         NCClass)
        // l
        add("!less",        NCCompare)
        add("!less-or-eq",  NCCompare)
        // m
        add("!mcall",       NCMCall)
        add("!mul",         NCMath)
        // n
        add("!neg",         NCMath)
        add("new",          NCNew)
        add("!new-array",   NCNewArray)
        add("!not",         NCNot)
        add("!not-eq",      NCCompare)
        add("ns",           NCDefault)
        // o
        add("!obj",         NCClass)
        add("!or",          NCMath)
        // r
        add("!rem",         NCMath)
        add("ret",          NCRet)
        add("!rfn",         NCRFn)
        // s
        add("set!",         NCSet)
        add("sns",          NCDefault)
        add("!sub",         NCMath)
        // u
        add("unit",         NCUnit)
        // v
        add("value",        NCValue)
        // x
        add("!xor",         NCMath)

        // Аннотации
        add("@abstract",    NCDefault)
        add("@final",       NCDefault)
        add("@open",        NCDefault)
        add("@static",      NCDefault)
        add("@varargs",     NCDefault)
    }
}