package ru.DmN.pht.std.compiler.java

import ru.DmN.siberia.compilers.NCDefault
import ru.DmN.siberia.utils.ModuleCompilers
import ru.DmN.pht.std.Pihta
import ru.DmN.pht.std.compiler.java.compilers.*
import ru.DmN.phtx.pcl.compiler.json.compilers.NCNamed

object PihtaJava : ModuleCompilers(Pihta) {
    override fun onInitialize() {
        // a
        add("!add",         NCMath)
        add("!aget",        NCAGet)
        add("!alias-type",  NCSkip)
        add("!and",         NCMath)
        add("array-size",   NCArraySize)
        add("!as",          NCAs)
        add("!aset",        NCASet)
        // b
        add("body",         NCBody)
        add("!break",       NCBreak)
        // c
        add("!catch",       NCCatch)
        add("!cls",         NCClass)
        add("!continue",    NCContinue)
        add("ctor",         NCDefn)
        add("!cycle",       NCCycle)
        // d
        add("!dec",         NCIncDec)
        add("!def",         NCDef)
        add("!defn",        NCDefn)
        add("!div",         NCMath)
        // e
        add("efld",         NCEField)
        add("efn",          NCDefn)
        add("!enum",        NCClass)
        add("!eq",          NCCompare)
        // f
        add("!fget",        NCFGet)
        add("!fld",         NCField)
        add("!fn",          NCFn)
        add("fset",         NCFSet)
        // g
        add("get",          NCGetA)
        add("get-or-name!", NCGetB)
        add("!great",       NCCompare)
        add("!great-or-eq", NCCompare)
        // i
        add("!if",          NCIf)
        add("!inc",         NCIncDec)
        add("!itf",         NCClass)
        // l
        add("!less",        NCCompare)
        add("!less-or-eq",  NCCompare)
        // m
        add("!mcall",       NCMCall)
        add("!mul",         NCMath)
        // n
        add("!named-block", NCNamedBlock)
        add("!neg",         NCMath)
        add("!new",         NCNew)
        add("!new-array",   NCNewArray)
        add("!not",         NCCompare)
        add("!not-eq",      NCCompare)
        add("!ns",          NCDefault)
        // o
        add("!obj",         NCClass)
        add("!or",          NCMath)
        // r
        add("!rem",         NCMath)
        add("!ret",         NCRet)
        // s
        add("set!",         NCSet)
        add("!shift-left",  NCMath)
        add("!shift-right", NCMath)
        add("sns",          NCDefault)
        add("!sub",         NCMath)
        // t
        add("throw",        NCThrow)
        // u
        add("unit",         NCUnit)
        // v
        add("value",        NCValue)
        // x
        add("!xor",         NCMath)

        // Аннотации
        add("@abstract",    NCDefault)
        add("@final",       NCDefault)
        add("@open",        NCDefault)
        add("@static",      NCDefault)
        add("@varargs",     NCDefault)
    }
}